name: CD-GitHub

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack
      run: |
        dotnet pack src/PackSite.Library.StringUnformatter.sln --configuration Release

    - name: Deploy to GitHub Package Registry
      run: |
        dotnet nuget push src/PackSite.Library.StringUnformatter/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
