name: CD-NuGet

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: |
        dotnet pack src/PackSite.Library.StringUnformatter.sln --configuration Release

    - name: Deploy
      run: |
        dotnet nuget push src/PackSite.Library.StringUnformatter/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
